services:
  postgres:
    image: postgres:14
    container_name: collector-postgres
    restart: always
    environment:
      POSTGRES_USER: collector_user
      POSTGRES_PASSWORD: collector_password
      POSTGRES_DB: collector_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
