version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: collector-postgres
    restart: always
    environment:
      POSTGRES_USER: collector_user
      POSTGRES_PASSWORD: collector_password
      POSTGRES_DB: collector_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: collector-keycloak
    restart: always
    depends_on:
      - postgres
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: collector_db
      KC_DB_USERNAME: collector_user
      KC_DB_PASSWORD: collector_password
      KC_HOSTNAME: localhost
    command:
      - start-dev
    ports:
      - "8081:8080"

  mailcatcher:
    image: dockage/mailcatcher:latest
    container_name: mailcatcher
    restart: always
    ports:
      - "1025:1025"
      - "1080:1080"

  prometheus:
    image: prom/prometheus:latest
    container_name: collector-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    container_name: collector-grafana
    restart: unless-stopped
    ports:
      - "3700:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  sonar_db:
    image: postgres:15
    container_name: collector-sonar-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_db_data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:lts-community
    container_name: collector-sonarqube
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9900:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

volumes:
  pgdata:
  grafana_data:
  sonar_db_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
